import { __ } from '@wordpress/i18n';

export const labels = {
	width: __('Width', 'designsetgo'),
	minWidth: __('Minimum width', 'designsetgo'),
	maxWidth: __('Maximum width', 'designsetgo'),
	height: __('Height', 'designsetgo'),
	minHeight: __('Minimum height', 'designsetgo'),
	maxHeight: __('Maximum height', 'designsetgo'),
	aspectRatio: __('Aspect ratio', 'designsetgo'),
	overflow: __('Overflow', 'designsetgo'),
	position: __('Position', 'designsetgo'),
	top: __('Top', 'designsetgo'),
	right: __('Right', 'designsetgo'),
	bottom: __('Bottom', 'designsetgo'),
	left: __('Left', 'designsetgo'),
	zIndex: __('Layer order', 'designsetgo'),
	direction: __('Direction', 'designsetgo'),
	wrap: __('Wrap', 'designsetgo'),
	justifyContent: __('Justification', 'designsetgo'),
	alignItems: __('Alignment', 'designsetgo'),
	gap: __('Gap', 'designsetgo'),
	rowGap: __('Row gap', 'designsetgo'),
	columnGap: __('Column gap', 'designsetgo'),
	paddingTop: __('Top padding', 'designsetgo'),
	paddingRight: __('Right padding', 'designsetgo'),
	paddingBottom: __('Bottom padding', 'designsetgo'),
	paddingLeft: __('Left padding', 'designsetgo'),
	contentWidth: __('Content width', 'designsetgo'),
	gridTemplateRows: __('Grid rows', 'designsetgo'),
	gridTemplateAreas: __('Named grid areas', 'designsetgo'),
	flexBasis: __('Flex basis', 'designsetgo'),
	flexGrow: __('Flex grow', 'designsetgo'),
	flexShrink: __('Flex shrink', 'designsetgo'),
	alignSelf: __('Self alignment', 'designsetgo'),
	gridColumn: __('Grid column', 'designsetgo'),
	gridRow: __('Grid row', 'designsetgo'),
	gridArea: __('Grid area', 'designsetgo'),
};

export const groupFields = {
	layout: [
		'direction',
		'wrap',
		'justifyContent',
		'alignItems',
		'gap',
		'rowGap',
		'columnGap',
		'paddingTop',
		'paddingRight',
		'paddingBottom',
		'paddingLeft',
		'contentWidth',
		'gridTemplateRows',
		'gridTemplateAreas',
	],
	size: [
		'width',
		'minWidth',
		'maxWidth',
		'height',
		'minHeight',
		'maxHeight',
		'aspectRatio',
		'overflow',
	],
	placement: [
		'position',
		'top',
		'right',
		'bottom',
		'left',
		'zIndex',
		'flexBasis',
		'flexGrow',
		'flexShrink',
		'alignSelf',
		'gridColumn',
		'gridRow',
		'gridArea',
	],
};

export const valueLabels = {
	auto: __('Auto', 'designsetgo'),
	normal: __('Normal', 'designsetgo'),
	row: __('Row', 'designsetgo'),
	column: __('Column', 'designsetgo'),
	'row-reverse': __('Reversed row', 'designsetgo'),
	'column-reverse': __('Reversed column', 'designsetgo'),
	nowrap: __('No wrap', 'designsetgo'),
	wrap: __('Wrap', 'designsetgo'),
	'wrap-reverse': __('Reversed wrap', 'designsetgo'),
	start: __('Start', 'designsetgo'),
	end: __('End', 'designsetgo'),
	center: __('Center', 'designsetgo'),
	'flex-start': __('Flex start', 'designsetgo'),
	'flex-end': __('Flex end', 'designsetgo'),
	'space-between': __('Space between', 'designsetgo'),
	'space-around': __('Space around', 'designsetgo'),
	'space-evenly': __('Space evenly', 'designsetgo'),
	stretch: __('Stretch', 'designsetgo'),
	baseline: __('Baseline', 'designsetgo'),
	visible: __('Visible', 'designsetgo'),
	hidden: __('Hidden', 'designsetgo'),
	clip: __('Clip', 'designsetgo'),
	scroll: __('Scroll', 'designsetgo'),
	static: __('Static', 'designsetgo'),
	relative: __('Relative', 'designsetgo'),
	absolute: __('Absolute', 'designsetgo'),
};
