<?php
/**
 * Reads the committed JS-registered-attribute manifest so PHP's
 * Tree_Attributes can tell "known to JS, just not to PHP's own
 * WP_Block_Type->attributes" (e.g. `anchor` — added to the block's
 * attributes only by client-side block-support JS, never by
 * wp-includes/block-supports/anchor.php — or any DesignSetGo extension
 * attribute, added only by a `blocks.registerBlockType` JS filter) apart
 * from a genuinely unknown name.
 *
 * The manifest itself is generated by `npm run engine -- attribute-manifest
 * --out includes/abilities/agent-build/data/attribute-manifest.json` (see
 * src/engine/node/attribute-manifest.js) and covers every `designsetgo/*`
 * and `core/*` block type — the same universe the unknown-attribute-brief's
 * parity measurement used.
 *
 * @package DesignSetGo
 * @subpackage Abilities
 * @since 2.7.0
 */

namespace DesignSetGo\Abilities\Agent_Build;

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

/**
 * Attribute_Manifest class.
 */
class Attribute_Manifest {

	/** Path to the committed manifest, relative to this file. */
	const FILE = __DIR__ . '/data/attribute-manifest.json';

	/**
	 * Decoded manifest, loaded once per request.
	 *
	 * @var array<string, array<int, string>>|null
	 */
	private static $manifest = null;

	/**
	 * JS-registered attribute names for one block, per the committed
	 * manifest. Never throws: a missing or unreadable manifest file, or a
	 * block name the manifest doesn't cover, both resolve to an empty list
	 * rather than a fatal error - the engine's browser-side check is always
	 * the authoritative one, so a manifest problem should widen what PHP
	 * accepts unchecked, never crash the request.
	 *
	 * @param string $block_name Registered block name.
	 * @return array<int, string> Attribute names, or empty when unknown.
	 */
	public static function names_for( string $block_name ): array {
		$manifest = self::load();
		return isset( $manifest[ $block_name ] ) && is_array( $manifest[ $block_name ] )
			? $manifest[ $block_name ]
			: array();
	}

	/**
	 * Loads and caches the manifest file's decoded contents.
	 *
	 * @return array<string, array<int, string>> Decoded manifest, or empty
	 *   when the file is missing or not valid JSON.
	 */
	private static function load(): array {
		if ( null !== self::$manifest ) {
			return self::$manifest;
		}

		if ( ! file_exists( self::FILE ) ) {
			self::$manifest = array();
			return self::$manifest;
		}

		$contents = file_get_contents( self::FILE ); // phpcs:ignore WordPress.WP.AlternativeFunctions.file_get_contents_file_get_contents, WordPressVIPMinimum.Performance.FetchingRemoteData.FileGetContentsUnknown -- Reading a plugin-committed local JSON asset, not remote or user-controlled.
		$decoded  = is_string( $contents ) ? json_decode( $contents, true ) : null;

		self::$manifest = is_array( $decoded ) ? $decoded : array();
		return self::$manifest;
	}
}
